apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ctse-it19176802
  name: ctse-it19176802
spec:
  ports:
  - port: 8089
    protocol: TCP
    targetPort: 8089
  selector:
    app: ctse-it19176802
status:
  loadBalancer: {}